function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 11-Feb-2014 20:02:48

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'MarkerEdgeColor',[0 0 0],...
    'MarkerSize',15,...
    'LineWidth',2);
set(plot1(1),'Marker','v','LineStyle',':','Color',[0 0 1],...
    'DisplayName','Seperation');
set(plot1(2),'Marker','o','LineStyle','--','DisplayName','Reattachment',...
    'Color',[0 0 0]);

% Create xlabel
xlabel('Reynolds Number');

% Create ylabel
ylabel('Angle (degrees)');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.751213485560253 0.223640396996697 0.113587457230942 0.0950499935432693]);

